schemaVersion: 2.0.0

commandTests:
  - name: gcc compiler
    command: gcc
    args: ["--version"]
    expectedOutput: [".*gcc.*"]
  - name: g++ compiler
    command: g++
    args: ["--version"]
    expectedOutput: [".*g\\+\\+.*"]
  - name: make
    command: make
    args: ["--version"]
    expectedOutput: [".*GNU Make.*"]
  - name: ninja
    command: /root/ninja/ninja
    args: ["--version"]
    expectedOutput: [".*1.*"]
  - name: gcovr
    command: gcovr
    args: ["--version"]
    expectedOutput: [".*gcovr.*"]
  - name: ccache
    command: ccache
    args: ["--version"]
    expectedOutput: [".*ccache.*"]
  - name: doxygen
    command: doxygen
    args: ["--version"]
    expectedOutput: [".*1.*"]
  - name: cppcheck
    command: cppcheck
    args: ["--version"]
    expectedOutput: [".*Cppcheck.*"]
  - name: clang
    command: /root/llvm/bin/clang
    args: ["--version"]
    expectedOutput: [".*clang.*"]

fileExistenceTests:
  - name: "vcpkg"
    path: "/root/vcpkg"
    shouldExist: true
  - name: "llvm"
    path: "/root/llvm"
    shouldExist: true
